"""updated QR code data

Revision ID: 3d06831847b5
Revises: af32726a04a7
Create Date: 2023-10-29 12:12:26.554509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d06831847b5'
down_revision = 'af32726a04a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_data', sa.String(), nullable=True))
        batch_op.drop_column('qr_string')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_data', sa.String(), nullable=True))
        batch_op.drop_column('qr_string')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_data', sa.String(), nullable=True))
        batch_op.drop_column('qr_string')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_data', sa.String(), nullable=True))
        batch_op.drop_column('qr_string')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_data', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_data', sa.String(), nullable=True))
        batch_op.drop_column('qr_string')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('qr_data')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('qr_data')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('qr_data')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('qr_data')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('qr_data')

    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('qr_data')

    # ### end Alembic commands ###
