"""updated QR code string

Revision ID: af32726a04a7
Revises: ce28b6e5f59b
Create Date: 2023-10-29 11:56:38.665011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af32726a04a7'
down_revision = 'ce28b6e5f59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.String(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.String(), nullable=True))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.String(), nullable=True))

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_string', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('qr_string')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('qr_string')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('qr_string')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('qr_string')

    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('qr_string')

    # ### end Alembic commands ###
